[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "os"
version = "0.8.0-beta.3"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-beta.3"

[[dependency]]
org = "ballerina"
name = "lang.runtime"
version = "1.1.0-beta.3"
